version: '3'

# Configuración de los servidores que vamos a necesitar
services: 
  # Base de datos para WordPress
  mysql_wordpress:
    image: mysql:5.7
    container_name: mysql_container_wordpress
    restart: always
    ports:
      - 3307:3306  # Cambié el puerto del host de 3306 a 3307
    environment:
      MYSQL_ROOT_PASSWORD: Q@d1dZ8@%2
      MYSQL_USER: if0_38346359
      MYSQL_PASSWORD: m6hdATxi5C
      MYSQL_DATABASE: if0_38346359_dwes
    volumes:
      - mysql_data_wordpress:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

  # Base de datos para el proyecto PHP
  mysql_php:
    image: mysql:5.7
    container_name: mysql_container_php
    restart: always
    ports:
      - 3308:3306  # Usé un puerto diferente para el proyecto PHP
    environment:
      MYSQL_ROOT_PASSWORD: Q@d1dZ8@%2
      MYSQL_USER: if0_38346359
      MYSQL_PASSWORD: m6hdATxi5C
      MYSQL_DATABASE: if0_38346359_dwes
    volumes:
      - mysql_data_php:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

  # PhpMyAdmin para administrar la base de datos de WordPress
  phpmyadmin_wordpress:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container_wordpress
    restart: always
    environment:
      PMA_HOST: mysql_wordpress
      MYSQL_ROOT_PASSWORD: Q@d1dZ8@%2
    ports:
      - "8081:80"
    depends_on:
      - mysql_wordpress

  # PhpMyAdmin para administrar la base de datos del proyecto PHP
  phpmyadmin_php:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container_php
    restart: always
    environment:
      PMA_HOST: mysql_php
      MYSQL_ROOT_PASSWORD: Q@d1dZ8@%2
    ports:
      - "8082:80"
    depends_on:
      - mysql_php

  # Servidor Apache para el proyecto PHP
  apache:
    build: apache/
    container_name: apache_container
    ports:
      - 80:80
    volumes:
      - proyecto:/var/www/html/
    depends_on:
      - mysql_php
      - php

  # Servidor PHP
  php:
    build: php/
    ports:
      - 9000:9000
    container_name: php_container
    restart: always
    volumes:
      - proyecto:/var/www/html/
  
  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    restart: always
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: mysql_wordpress:3306
      WORDPRESS_DB_USER: if0_38346359
      WORDPRESS_DB_PASSWORD: m6hdATxi5C
      WORDPRESS_DB_NAME: if0_38346359_dwes
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql_wordpress

volumes:
  proyecto:
  mysql_data_wordpress:
  mysql_data_php:
  wordpress:
